config/routes.rb
Calib::Application.routes.draw do

  ActiveAdmin.routes(self)
  devise_for :users
  root 'machines#index'

  resources :machines do
    resources :services, only: :create
  end

  post '/machines/create' => 'machines#create'

  
  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :users
  has_many :machines
end

app/models/machine.rb
class Machine < ActiveRecord::Base
  belongs_to :customer
  has_many :services

  def self.search(search)
    if search
      find(:all, :conditions => ['name ILIKE ?', "%#{search}%"])
    else
      find(:all)
    end 
  end
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :machine
  
end

app/models/side.rb
class Side < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :machines
  belongs_to :side
  belongs_to :customer

  def is_admin?
  self.admin?
  return true
  end

  def company_name
    if side_id == 1
      return customer.name
    else
      return "Supplier"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # Prevent CSRF attacks by raising an exception.
   # For APIs, you may want to use :null_session instead.
   protect_from_forgery with: :exception

   before_action :configure_permitted_parameters, if: :devise_controller?
   protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name, :side_id, :customer_id) }
  end

  def authenticate_admin_user!
  redirect_to new_user_session_path unless current_user.try(:is_admin?)
  end

end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  respond_to :html, :js
  
  def index
    @machines = Machine.search(params[:search])
  end

  def new
    @machine = Machine.new
  end

  def create
    machine = Machine.create(machine_params)
    respond_to do |format|
      format.html {
        redirect_to root_path
      }
      format.js {
        render json: machine.as_json
      }
    end
  end

  def machine_params()
    params.require(:machine).permit(:name, :description, :location, :year, :customer_id)
  end
  
  def edit
    @machine = Machine.find(params[:id])
  end

  def update
    @machine = Machine.find(params[:id])
    @machine.update_attributes(machine_params)
    redirect_to root_path
  end

  def show
    @machine = Machine.find(params[:id])
    @service = Service.new
    
  end
  

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def create
    @machine = Machine.find(params[:machine_id])
    @machine.services.create(service_params)
    redirect_to machine_path(@machine)
  end

  private

  def service_params
    params.require(:service).permit(:description, :date, :supplier, :place, :order)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calib</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <ul class="nav navbar-nav">
      <li><%= link_to 'Calibration Services Tracking', root_path, class: 'navbar_brand'%></li>
      </ul>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Create Machine', new_machine_path, class: 'navbar_brand'%></li>
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <%=form_tag machines_path, :method => 'get' do %>
          <p>
          <%= text_field_tag :search, params[:search] %>
          <%= submit_tag "Search", :name => nil, class: 'btn btn-default' %>
          </p>
        <% end %>
      </form>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>

        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
        <%if user_signed_in?%>
          <% if current_user.admin?%>
            <li><%=link_to 'Admin', admin_dashboard_path%></li>

          <%end%>
        <%end%>

        <ul class="nav navbar-nav">
        <li class="company-name"><%=current_user.company_name%></li>
        </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% if notice.present?%>
  <p class="alert alert-info"><%= notice %></p>
<%end%>
<%if alert.present?%>
<p class="alert alert-danger"><%= alert %></p>
<%end%>

<%= yield %>

</body>
</html>

app/views/machines/_form.html.erb
<div class="booyah-box col-xs-6 col-xs-offset-1">
  <h1>Input Your Machine Details</h1>
  <%=simple_form_for @machine, html: { class: "new_machine"},  remote: true do |f| %>
    <%=f.input :name%>
    <%=f.input :description%>
    <%=f.input :location%>
    <%=f.input :year%>
    <%=f.association :customer, collection: Customer.all , prompt: "Choose a customer"%>
    <br />
    <%=f.submit 'Create', class: 'btn btn-primary'%>
  <%end%>
  <br />
</div>

app/views/machines/create.js.erb
$('.new_machine').remove();
$('#new_link').show();

app/views/machines/edit.html.erb
<div class="booyah-box col-xs-6 col-xs-offset-1">
  <h1>Input Your Machine Details</h1>
  <%=simple_form_for @machine do |f| %>
    <%=f.input :name%>
    <%=f.input :description%>
    <%=f.input :location%>
    <%=f.input :year%>
    <%#=f.association :user, collection: User.where(side_id: 1), prompt: "Choose a customer"%>
    <br />
    <%=f.submit 'Edit', class: 'btn btn-primary'%>
  <%end%>
  <br />
</div>


app/views/machines/index.html.erb
<h1>List of machines</h1>


<div id="newMachineForm" class="booyah-box col-xs-6 col-xs-offset-1">
 <h1>Input Your Machine Details</h1>
 <div class='row'>
 <label class = 'col-md-3'>Name:</label>
 <input class = 'col-md-9 name'></input>
 </div>
 <div class='row'>
 <label class = 'col-md-3'>Description:</label>
 <input class = 'col-md-9 description'></input>
 </div>
 <div class = 'row'>
 <label class = 'col-md-3'>Location:</label>
 <input class = 'col-md-9 location'></input>
 </div>
 <div class = 'row'>
  <label class = 'col-md-3'>Year:</label>
 <input class = 'col-md-9 year'></input>
 </div>
    <br />
 <div class='btn btn-primary' onClick='createNewMachine()'>Create</div>
  <br />
</div>


<a href='#' id='showNewMachineFormLink' onClick="newMachineFormVisibility()">New Machine</a>
<%#<div id="machine-form" style="display:none;"></div>%>

<br />
  <div class='machines-list'>
    <%@machines.each do |m|%>
    <div class = "booyah-box col-xs-10 col-xs-offset-1">
      <h2 class="machine-name">Name:<%=m.name%></h2>
      <p>Description: <%=m.description%></p>
      <p>Location: <%=m.location%></p>
      <div class="row"><%= link_to 'Edit', edit_machine_path(m), class: 'btn btn-primary btn-sm'%>
      <%= link_to 'View details', machine_path(m), class: 'btn btn-primary btn-sm'%></div>
    </div>
    <%end%>
  </div>
    
    


  
      


app/views/machines/new.html.erb
<div class="booyah-box col-xs-6 col-xs-offset-1">
  <h1>Input Your Machine Details</h1>
  <%=simple_form_for @machine do |f| %>
    <%=f.input :name%>
    <%=f.input :description%>
    <%=f.input :location%>
    <%=f.input :year%>
    <%=f.association :customer, collection: Customer.all , prompt: "Choose a customer"%>
    <br />
    <%=f.submit 'Create', class: 'btn btn-primary'%>
  <%end%>
  <br />
</div>

app/views/machines/show.html.erb
<h1>Detail of machine</h1> <h1>Owner: 
<%=@machine.customer.name%></h1>
<br />

<ul>Name: <%= @machine.name%></ul>
<ul>Description: <%= @machine.description%></ul>
<ul>Location: <%= @machine.location%></ul>
<ul>Year of installation: <%= @machine.year%></ul>
<ul>Created at: <%= @machine.created_at%></ul>
<ul>Last update: <%= @machine.updated_at%></ul>

<br />

<button class="bt btn-primary btn-lg pull-left" data-toggle="modal" data-target="#myModal">
  Add a service
</button> 
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Add a service</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @service, url: machine_services_path(@machine) do |f| %>
        <%= f.input :description %>
        <%= f.input :place %>
        <%= f.input :date %>
        <%= f.input :supplier %>
        <%= f.input :order %>
      
      </div>
      <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <%=f.submit "Add a service", class: 'btn btn-primary' %>

      </div>
      <%end%>
    </div>
  </div>
</div>

<h1>List of services</h1>

<br />
<%@machine.services.each do |service|%>
  <div class ="booyah-box col-xs-12 col-sm-8 col-xs-1-offset">
  <ul><b>Service Nr:</b> <%= service.id%></ul>
  <ul><b>Description:</b> <%= service.description%></ul>
  <ul><b>Place of works:</b> <%= service.place%></ul>
  <ul><b>Customer Order:</b> <%= service.order%></ul>
  <ul><b>Date of Works:</b> <%= service.date%></ul>
  <ul><b>Supplier:</b> <%= service.supplier%></ul>
  <ul><b>Status:</b> <%= service.status%></ul>
  </div>

  <br />
<%end%>
















  